# Generated by Django 5.0.1 on 2024-01-16 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TS', 'Clothes'), ('AC', 'Accessories'), ('BK', 'Books'), ('PT', 'Painting')], max_length=15)),
                ('product_type', models.CharField(blank=True, choices=[('T-shirt', 'T-shirt'), ('Kurta', 'Kurta'), ('Mug', 'Mug'), ('Key-chain', 'Key-chain'), ('watch', 'watch')], default=None, max_length=50, null=True)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='upload_products')),
                ('left_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('right_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('product_video', models.FileField(blank=True, default='', null=True, upload_to='productvideos')),
                ('product_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_date1', models.CharField(blank=True, max_length=200, null=True)),
                ('product_video_url', models.URLField(blank=True, null=True)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
            ],
        ),
    ]
