# Generated by Django 5.0.1 on 2024-01-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('heading1', models.CharField(blank=True, max_length=50, null=True)),
                ('heading2', models.CharField(blank=True, max_length=50, null=True)),
                ('heading3', models.CharField(blank=True, max_length=50, null=True)),
                ('heading4', models.CharField(blank=True, max_length=50, null=True)),
                ('heading5', models.CharField(blank=True, max_length=50, null=True)),
                ('heading6', models.CharField(blank=True, max_length=50, null=True)),
                ('heading7', models.CharField(blank=True, max_length=50, null=True)),
                ('heading8', models.CharField(blank=True, max_length=50, null=True)),
                ('heading9', models.CharField(blank=True, max_length=50, null=True)),
                ('heading10', models.CharField(blank=True, max_length=50, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('content6', models.TextField(blank=True, null=True)),
                ('content7', models.TextField(blank=True, null=True)),
                ('content8', models.TextField(blank=True, null=True)),
                ('content9', models.TextField(blank=True, null=True)),
                ('content10', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
