# Generated by Django 5.0.1 on 2024-01-17 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
