# Generated by Django 5.0.1 on 2024-01-17 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_blogpost_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
