# Generated by Django 5.0.1 on 2024-01-18 12:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_blogpost_blog_created_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('TS', 'Clothes'), ('AC', 'Accessories'), ('BK', 'Books'), ('PT', 'Painting')], max_length=50)),
                ('product_type', models.CharField(choices=[('T-shirt', 'T-shirt'), ('Kurta', 'Kurta'), ('Mug', 'Mug'), ('Key-chain', 'Key-chain'), ('watch', 'watch')], max_length=50)),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('back_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('left_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('right_image', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('product_video', models.FileField(blank=True, default='', null=True, upload_to='productvideos')),
                ('product_video_url', models.URLField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('product_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('product_date1', models.CharField(blank=True, max_length=200, null=True)),
                ('product_approved', models.BooleanField(default=False)),
                ('product_reject', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
