# Generated by Django 5.0.1 on 2024-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_product_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_seller',
        ),
    ]
