# Generated by Django 5.0.1 on 2024-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_product',
            name='actual_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='admin_product',
            name='discount_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
