# Generated by Django 5.0.1 on 2024-02-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_admin_product_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_product',
            name='category',
            field=models.CharField(blank=True, choices=[('TS', 'Clothes'), ('AC', 'Accessories'), ('BK', 'Books'), ('PT', 'Painting')], max_length=15, null=True),
        ),
    ]
