# Generated by Django 5.0.1 on 2024-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_trackingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdetail',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
