# Generated by Django 5.0.1 on 2024-03-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_trackingdetail_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='customized_Designed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='upload_products')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='upload_products')),
            ],
        ),
    ]
