# Generated by Django 5.0.1 on 2024-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_customized_designed'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(max_length=100, null=True)),
                ('smtp_username', models.CharField(max_length=100, null=True)),
                ('smtp_password', models.CharField(max_length=100, null=True)),
                ('smtp_server', models.CharField(max_length=100, null=True)),
                ('smtp_port', models.CharField(max_length=100, null=True)),
                ('smtp_security', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
