# Generated by Django 5.0.1 on 2024-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
