# Generated by Django 5.0.1 on 2024-02-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderplaced_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='location1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='location2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='location3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='update_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
