# Generated by Django 5.0.1 on 2024-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_orderplaced_datetime_orderplaced_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='return_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
