# Generated by Django 5.0.1 on 2024-02-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_orderplaced_size_canceledorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
