# Generated by Django 5.0.1 on 2024-03-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_orderplaced_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
