# Generated by Django 5.0.1 on 2024-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_cart_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image_src',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customize'),
        ),
    ]
