# Generated by Django 5.0.1 on 2024-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_cart_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='customer_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload_products'),
        ),
    ]
