# Generated by Django 5.0.1 on 2024-04-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_customer_review_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='canceledorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='canceledorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='canceledorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
