# Generated by Django 5.0.4 on 2024-04-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_canceledorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_review',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
