# Generated by Django 5.0.4 on 2024-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_customer_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
