# Generated by Django 4.1.5 on 2024-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_orderplaced_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='selloship_order_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
