# Generated by Django 4.1.5 on 2024-05-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_orderplaced_selloship_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='selloship_order_id',
            new_name='selloship_id',
        ),
    ]
