# Generated by Django 5.0.1 on 2024-01-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_product',
            name='back_image',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='left_image',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_date1',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_video',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='product_video_url',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='right_image',
        ),
        migrations.RemoveField(
            model_name='seller_product',
            name='selling_price',
        ),
    ]
