# Generated by Django 5.0.1 on 2024-02-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_product_seller_skuid_product_seller_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_seller',
            name='age_range_description',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='bullet_point',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='manufacturer_contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='product_instruction',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='special_feature',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_seller',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
