# Generated by Django 5.0.1 on 2024-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_seller_age_range_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_seller',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
