# Generated by Django 5.0.1 on 2024-02-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_seller',
            name='prod_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
