# Generated by Django 5.0.1 on 2024-04-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_product_seller_product_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_seller',
            name='average_rating',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
