# Generated by Django 5.0.1 on 2024-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_product_seller_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_seller',
            name='discount_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
