# Generated by Django 5.0.4 on 2024-04-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_alter_product_seller_bullet_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Painting', 'Painting'), ('Customize', 'Customize'), ('Shivaji', 'Shivaji'), ('Babasaheb', 'Babasaheb'), ('abdulkalam', 'abdulkalam'), ('bhagatsingh', 'bhagatsingh'), ('gurunanak', 'gurunanak'), ('osho', 'osho'), ('savitriphule', 'savitriphule'), ('birsamunda', 'birsamunda'), ('buddha', 'buddha'), ('santkabir', 'santkabir'), ('martinluther', 'martinluther')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_seller',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Painting', 'Painting'), ('Customize', 'Customize'), ('Shivaji', 'Shivaji'), ('Babasaheb', 'Babasaheb'), ('abdulkalam', 'abdulkalam'), ('bhagatsingh', 'bhagatsingh'), ('gurunanak', 'gurunanak'), ('osho', 'osho'), ('savitriphule', 'savitriphule'), ('birsamunda', 'birsamunda'), ('buddha', 'buddha'), ('santkabir', 'santkabir'), ('martinluther', 'martinluther')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_seller',
            name='product_instruction',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product_seller',
            name='product_type',
            field=models.CharField(choices=[('T-shirt', 'tshhirt'), ('Kurta', 'Kurta'), ('Mug', 'Mug'), ('Key-chain', 'Key-chain'), ('watch', 'watch')], max_length=50),
        ),
    ]
