# Generated by Django 5.0.1 on 2024-02-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_orderplaced'),
        ('seller', '0008_product_seller_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('review_star', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('review', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('average_rating', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_seller')),
            ],
        ),
    ]
