# Generated by Django 5.0.1 on 2024-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_orderplaced_cancel_reason_orderplaced_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
