# Generated by Django 5.0.1 on 2024-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_orderplaced_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
