# Generated by Django 5.0.1 on 2024-02-28 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_cart_anonymous_user_id_cart_size'),
        ('login', '0007_seller_user_aadhar_card_seller_user_gst_document_and_more'),
        ('seller', '0011_commission_approved_by_commission_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('canceled_reason', models.TextField()),
                ('canceled_at', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer_user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_seller')),
            ],
        ),
    ]
