# Generated by Django 5.0.1 on 2024-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customize_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='Delivered',
            field=models.BooleanField(default=False),
        ),
    ]
