# Generated by Django 5.0.1 on 2024-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='image_src',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customize'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='jsonfiles',
            field=models.FileField(blank=True, default=None, null=True, upload_to='json_files'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='t_shirt_color',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='tshirt_owndesign_s',
            field=models.ImageField(blank=True, default='', null=True, upload_to='customize'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='tshirt_size',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
