# Generated by Django 5.0.1 on 2024-01-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vruser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
