# Generated by Django 5.0.1 on 2024-01-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_vruser_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vruser',
            name='username',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
