# Generated by Django 5.0.1 on 2024-01-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customer_user_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_user',
            name='commision',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='seller_user',
            name='seller_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller_user',
            name='seller_reject',
            field=models.BooleanField(default=False),
        ),
    ]
