# Generated by Django 5.0.1 on 2024-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_user',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='seller_user',
            name='gst_document',
            field=models.ImageField(blank=True, null=True, upload_to='gst_documents/'),
        ),
        migrations.AddField(
            model_name='seller_user',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to='pan_cards/'),
        ),
    ]
