# Generated by Django 5.0.1 on 2024-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_seller_user_aadhar_card_seller_user_gst_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vruser',
            name='company_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vruser',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
