# Generated by Django 5.0.1 on 2024-04-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_subscribedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
