# Generated by Django 5.0.1 on 2024-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_vruser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logo/')),
                ('store_email', models.EmailField(max_length=254)),
                ('store_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('store_address', models.CharField(blank=True, max_length=50, null=True)),
                ('store_description', models.TextField(blank=True, max_length=100, null=True)),
                ('store_city', models.CharField(blank=True, max_length=50, null=True)),
                ('store_state', models.CharField(blank=True, max_length=50, null=True)),
                ('store_pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
