# Generated by Django 4.1.5 on 2024-05-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vruser',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vruser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
